# Tâche 5

In [121]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from jupyter_jsmol.pymatgen import quick_view
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [122]:
with MPRester("MVjrPtjUJ4K2IdZ4zJmL2QqGBqEUCt6C") as m:
    prim_struc = m.get_structure_by_material_id("mp-961648")
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()
sites = conv_struc.sites

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [123]:
# Représentation 3D de KBaP
view = quick_view(conv_struc)
display(view)
# green : Ba2+
# purple : K+
# orange : P3-

JsmolView(layout=Layout(align_self='stretch', height='400px'))

#### Petit rappel: Les opérations de symétrie s'applique de la manière suivante : (matrice de rotation de l'opération de symétrie) * (coordonnées réduites de l'atome) + (vecteur de translation de l'opération de symétrie).

# Première symétrie

In [124]:
i = 6
print(symmops[i],"\n")

Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 



Comme premier élement de symétrie, nous avons une rotation d'ordre 2 (rotation de 180°) autour de l'axe b (voir représentation jsmol) qui transforme les coordonnées (x,y,z) en (-x,y,-z) avec la matrice de rotation : $\begin{pmatrix}
-1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & -1
\end{pmatrix}$ et le vecteur de translation : $\begin{pmatrix}
0 & 0 & 0
\end{pmatrix}$.

In [125]:
l = 2
at1 = sites[l]
op1 = symmops[i]

pos_init1 = at1.frac_coords
print("Position initiale:",pos_init1)

pos_final1 = op1.operate(pos_init1)
print("Position finale après symétrie:",pos_final1)

Position initiale: [0.75 0.25 0.75]
Position finale après symétrie: [-0.75  0.25 -0.75]


L'opération de symétrie de rotation est appliquée à un atome K+ qui passe des coordonnées réduites $\begin{pmatrix}
0.75 & 0.25 & 0.75
\end{pmatrix}$
aux coordonnées réduites $\begin{pmatrix}
-0.75 & 0.75 & -0.75
\end{pmatrix}$.

In [126]:
# Représentation 3D par jsmol + image pour github
view1 = quick_view(conv_struc)
display(view1)
view1.script('draw SYMOP ' + str(i+1) + ' {atomno = ' + str(4) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

![Symétrie de rotation](Images/rotation.jpg)

# Deuxième symétrie

In [127]:
j = 5
print(symmops[j],"\n")

Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.] 



Comme deuxième élement de symétrie, nous avons un plan miroir $\begin{pmatrix}
1 & \bar{1} & 0
\end{pmatrix}
$ qui transforme les coordonnées (x,y,z) en (y,x,z) avec la matrice de rotation : $\begin{pmatrix}
0 & 1 & 0\\
1 & 0 & 0\\
0 & 0 & 1
\end{pmatrix}$ et le vecteur de translation : $\begin{pmatrix}
0 & 0 & 0
\end{pmatrix}$.

In [128]:
m = 10
at2 = sites[m]
op2 = symmops[j]

pos_init2 = at2.frac_coords
print("Position initiale::",pos_init2)
 
pos_final2 = op2.operate(pos_init2)
print("Position finale après symétrie:",pos_final2)

Position initiale:: [0.5 0.  0.5]
Position finale après symétrie: [0.  0.5 0.5]


L'opération de symétrie de plan miroir est appliquée à un atome Ba2+ qui passe des coordonnées réduites $\begin{pmatrix}
0.5 & 0. & 0.5
\end{pmatrix}$
aux coordonnées réduites $\begin{pmatrix}
0. & 0.5 & 0.5
\end{pmatrix}$.

In [129]:
# Représentation 3D par jsmol + image pour github
view2 = quick_view(conv_struc)
display(view2)
view2.script('draw SYMOP ' + str(j + 1) + ' {atomno = ' + str(m + 1) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

![Symétrie de plan miroir](Images/plan.jpg)

# Troisième symétrie

In [130]:
k = 24
print(symmops[k],"\n")

Rot:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tau
[0.5 0.5 0. ] 



Comme troisième élement de symétrie, nous avons une translation simple qui transforme les coordonnées (x,y,z) en (x+0.5,y+0.5,z) avec la matrice de rotation : $\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}$ qui est la matrice unité et le vecteur de translation : $\begin{pmatrix}
0.5 & 0.5 & 0
\end{pmatrix}$.

In [131]:
n = 8
at3 = sites[n]
op3 = symmops[k]

pos_init3 = at3.frac_coords
print("Position initiale:",pos_init3)
 
pos_final3 = op3.operate(pos_init3)
print("Position finale après symétrie:",pos_final3)

Position initiale: [0. 0. 0.]
Position finale après symétrie: [0.5 0.5 0. ]


L'opération de symétrie de translation simple est appliquée à un atome P3- qui passe des coordonnées réduites $\begin{pmatrix}
0. & 0. & 0.
\end{pmatrix}$
aux coordonnées réduites $\begin{pmatrix}
0.5 & 0.5 & 0.5
\end{pmatrix}$.

In [132]:
# Représentation 3D par jsmol + image pour github
view3 = quick_view(conv_struc)
display(view3)
view3.script('draw SYMOP ' + str(k + 1) + ' {atomno = ' + str(n + 1) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

![Symétrie de translation](Images/translation.jpg)